server:
  port: 5285
spring:
  application:
    name: BUS-EXAMPLE
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:10001/eureka/
    register-with-eureka: true
    fetch-registry: true
    # 定时刷新本地缓存的时间
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    # 没有心跳的淘汰时间间隔
    lease-expiration-duration-in-seconds: 10
    # 心跳间隔
    lease-renewal-interval-in-seconds: 5

